<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["lawyers/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["lawyers/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Id</th>
            <th>First Of Name</th>
            <th>Last Of Name</th>
            <th>Email</th>
            <th>Fee</th>
            <th>Address</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $lawyer): ?>
            <tr>
                <td><?php echo $lawyer->getId() ?></td>
            <td><?php echo $lawyer->getFirstName() ?></td>
            <td><?php echo $lawyer->getLastName() ?></td>
            <td><?php echo $lawyer->getEmail() ?></td>
            <td><?php echo $lawyer->getFee() ?></td>
            <td><?php echo $lawyer->getAddress() ?></td>

                <td><?php echo $this->tag->linkTo(["lawyers/edit/" . $lawyer->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["lawyers/delete/" . $lawyer->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("lawyers/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("lawyers/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("lawyers/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("lawyers/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
