<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["review", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit review
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "review/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldAppointmentId" class="col-sm-2 control-label">Appointment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["appointment_id", "type" => "number", "class" => "form-control", "id" => "fieldAppointmentId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldClientId" class="col-sm-2 control-label">Client</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["client_id", "type" => "number", "class" => "form-control", "id" => "fieldClientId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLawyerId" class="col-sm-2 control-label">Lawyer</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lawyer_id", "type" => "number", "class" => "form-control", "id" => "fieldLawyerId"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
