<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search review
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["review/new", "Create review"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "review/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldAppintmentId" class="col-sm-2 control-label">Appointment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["appintment_id", "type" => "number", "class" => "form-control", "id" => "fieldAppintmentId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldClientId" class="col-sm-2 control-label">Client</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["client_id", "type" => "number", "class" => "form-control", "id" => "fieldClientId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLawyerId" class="col-sm-2 control-label">Lawyer</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lawyer_id", "type" => "number", "class" => "form-control", "id" => "fieldLawyerId"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
