<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["index", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Make an appointment
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "review/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?><div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAppointmentDate" class="col-sm-2 control-label">Appointment Date</label>
    <div class="col-sm-10">
        <?php
        $currentDate = date("Y-m-d"); // Get the current date in the format "YYYY-MM-DD"
        echo $this->tag->dateField(["appointment_date", "size" => 30, "class" => "form-control", "id" => "fieldAppointmentDate", "min" => $currentDate]);
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStartTime" class="col-sm-2 control-label">Start Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->timeField(["start_time", "size" => 30, "class" => "form-control", "id" => "fieldStartTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndTime" class="col-sm-2 control-label">End Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->timeField(["end_time", "size" => 30, "class" => "form-control", "id" => "fieldEndTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAppointmentTime" class="col-sm-2 control-label">Appointment Time</label>
    <div class="col-sm-10">
        <select name="appointment_time" class="form-control" id="fieldAppointmentTime">
            <option value="8:00-9:00">8:00-9:00</option>
            <option value="9:00-10:00">9:00-10:00</option>
            <option value="10:00-11:00">10:00-11:00</option>
            <option value="11:00-12:00">11:00-12:00</option>
            <option value="12:00-13:00">12:00-13:00</option>
            <option value="13:00-14:00">13:00-14:00</option>
            <option value="14:00-15:00">14:00-15:00</option>
            <option value="15:00-16:00">15:00-16:00</option>
            <option value="16:00-17:00">16:00-17:00</option>
            <option value="17:00-18:00">17:00-18:00</option>
            <option value="18:00-19:00">18:00-19:00</option>
        </select>
    </div>
</div>

<input type="hidden" name="lawyerId" value="<?php echo $lawyerId ?>">

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
