<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["appointments", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit appointment
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "appointments/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAppointmentDate" class="col-sm-2 control-label">Appointment Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(["appointment_date", "type" => "date", "class" => "form-control", "id" => "fieldAppointmentDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <select name="status" id="fieldStatus" class="form-control">
            <option value="approved">Approved</option>
            <option value="declined">Declined</option>
        </select>
    </div>
</div>

<div class="form-group">
    <label for="fieldStartTime" class="col-sm-2 control-label">Start Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->timeField(["start_time", "size" => 30, "class" => "form-control", "id" => "fieldStartTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndTime" class="col-sm-2 control-label">End Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->timeField(["end_time", "size" => 30, "class" => "form-control", "id" => "fieldEndTime"]) ?>
    </div>
</div>



<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
