<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["index/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["appointments/displayCalendar", "Show Calendar "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Appointments list</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>Start Of Time</th>
                <th>End Of Time</th>
                <th>Status</th>
                <th>Title</th>
                <th>Appointment Date</th>
                <th>Approve</th>
                <th>Decline</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
        <?php foreach ($appointments as $appointment): ?>
            <tr>
                <td><?php echo $appointment->getId() ?></td>
                <td><?php echo $appointment->getStartTime() ?></td>
                <td><?php echo $appointment->getEndTime() ?></td>
                <td><?php echo $appointment->getStatus() ?></td>
                <td><?php echo $appointment->getTitle() ?></td>
                <td><?php echo $appointment->getAppointmentDate() ?></td>
                <td><?php echo $this->tag->linkTo(["appointments/approve/" . $appointment->getId(), "Approve"]); ?></td>
                <td><?php echo $this->tag->linkTo(["appointments/decline/" . $appointment->getId(), "Decline"]); ?></td>
                <td><?php echo $this->tag->linkTo(["appointments/edit/" . $appointment->getId(), "Edit"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11 text-center">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("appointments/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("appointments/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("appointments/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("appointments/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
